### ISSUE TITLE
校园网开恩了

### ISSUE THREAD

**Issue by Akarinnnnn** [Uni-Gal/UniGal.Compilers#1]
近段时间script项目不太稳定，编译器这边也不好做
所以这次👴就光明正大鸽一个月

**Comment by LaoshuBaby** [comment]
俺也一样.jpg

----------
From GitKraken 7.5.0

**Comment by RimoChan** [comment]
俺也一样.avi

**Comment by Akarinnnnn** [comment]
身体不太行，再鸽一个月
![8$WQ)WGK2(VU)~_$72W@4`U](https://user-images.githubusercontent.com/43724908/108686607-9eeacc80-7530-11eb-953e-3d876979753c.jpg)

**Comment by RimoChan** [comment]
> 身体不太行，再鸽一个月
> ![8$WQ)WGK2(VU)~_$72W@4`U](https://user-images.githubusercontent.com/43724908/108686607-9eeacc80-7530-11eb-953e-3d876979753c.jpg)

把衣服掀起来，我来帮你治疗一下~

**Comment by Akarinnnnn** [comment]
好点了

**Comment by Akarinnnnn** [comment]
如题

**Comment by Akarinnnnn** [comment]
@LaoshuBaby 代推

**Comment by LaoshuBaby** [comment]
> 
> 
> @LaoshuBaby 代推

代push的内容以全量压缩包由各种方式交给鼠宝宝

鼠宝宝会在commit时加上前缀[Akarinnnnn]并在注释里艾特的~

https://github.com/Uni-Gal/UniGal-EnforcementProposal/blob/main/UEE/README.md

**Comment by RimoChan** [comment]
啊，不用，你先commit，然后把commit后的仓库发给老鼠宝宝，然后她push就行了

**Comment by Akarinnnnn** [comment]
对啊，push到本地文件夹再做个压缩包

**Comment by LaoshuBaby** [comment]
> 
> 
> 啊，不用，你先commit，然后把commit后的仓库发给老鼠宝宝，然后她push就行了

今日鬼故事两则

![图片](https://user-images.githubusercontent.com/42690037/109491984-3f0e9b80-7ac5-11eb-858f-dbd738f401fa.png)
![图片](https://user-images.githubusercontent.com/42690037/109491936-2f8f5280-7ac5-11eb-9766-160674b7029d.png)

**Comment by Akarinnnnn** [comment]
学校似乎施舍了一点，有时上的来。要是上的来就自己推送了。

**Comment by Akarinnnnn** [comment]
校园网又开恩了，啥时候不行了我再找人代推把……
我直呼看不懂

**Comment by LaoshuBaby** [comment]
你啥时候想推的时候就再来一发上次那操作
反正命令我都存了
照着来就是





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Fa鸽"<notifications@github.com&gt;; 
发送时间: 2021年3月3日(星期三) 晚上6:25
收件人: "Uni-Gal/UniGal.Compilers"<UniGal.Compilers@noreply.github.com&gt;; 
抄送: "LAOSHU_CN"<keaitianxinmail@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [Uni-Gal/UniGal.Compilers] 校园网开恩了 (#1)





 
Closed #1.
 
&mdash;
