### ISSUE TITLE
关于有无必要为两个不同的编译器分支分别开代号的问题

### ISSUE THREAD

**Issue by LaoshuBaby** [Uni-Gal/UniGal.Compilers#2]
（嗯只是有了这个想法，所以先放在这儿x
（管他的，等Fa鸽回来再说也不迟

**Comment by Akarinnnnn** [comment]
这边这个是新的，拓展性更好。
问题是鸽，我太鸽了![1](https://user-images.githubusercontent.com/43724908/108686607-9eeacc80-7530-11eb-953e-3d876979753c.jpg)

**Comment by Akarinnnnn** [comment]
另一个问题在于：这边开发预计时间很长，另一边已经能用了，急着用建议去另一边看看。  
我这玩意预计复用起来比较快，模块化了，而且我有自信我把各个模块分的还行
